services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    # command: python ..run.py
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    # environment:
    #   DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/mydb

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
